Documentation/8 update plantuml dependency
itsallcode/openfasttrace-architecture-template pull request #9
Opened 2024-01-06 18:49 UTC by redcatbear

Updated pandoc dependency to fix CVE-2023-3432.
Updated build to new plugins.
Improved documentation.

2024-01-06 23:26 UTC, kaklakariada approved these changes

2024-01-06 23:28 UTC, kaklakariada requested changes
Increment version in pom

2024-01-12 11:48 UTC, redcatbear commented
V 1.0.0 has never been released, so I think this should be the first 1.0.0 release

2024-01-12 18:53 UTC, kaklakariada commented
Ok. I didn't see the version in the diff.

2024-01-12 18:53 UTC, kaklakariada approved these changes
Increment version in Pom

2024-01-14 18:15 UTC, merged